name: Tests

on:
  push:
  pull_request:
  release:

jobs:
  ubuntu-oldest:
    name: Build on Ubuntu 20.04
    runs-on: ubuntu-20.04
    steps:

    - uses: actions/checkout@v2

    - uses: actions/checkout@v2
      with:
        repository: happycube/ld-decode-testdata
        path: testdata

    - name: Install dependencies
      timeout-minutes: 10
      run: |
        sudo apt-get update
        # Based on: https://github.com/happycube/ld-decode/wiki/Installation
        # Added: cmake libqt5opengl5-dev libqt5svg5-dev
        sudo apt-get install -y --no-install-recommends git cmake make python3-distutils python3-numpy python3-scipy python3-matplotlib git qt5-default libqt5opengl5-dev libqt5svg5-dev libqwt-qt5-dev libfftw3-dev python3-numba libavformat-dev libavcodec-dev libavutil-dev ffmpeg

    - name: Set up build dir
      timeout-minutes: 1
      run: mkdir obj && ln -s ../testdata obj/testdata

    - name: Configure
      timeout-minutes: 5
      run: cd obj && cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo ..

    - name: Build
      timeout-minutes: 15
      run: make -C obj VERBOSE=1

    - name: Install
      timeout-minutes: 5
      run: make -C obj install DESTDIR=/tmp/staging && ls -lR /tmp/staging

    - name: Run tests
      timeout-minutes: 10
      run: cd obj && ctest --output-on-failure

  ubuntu-newest:
    # XXX At present this uses Qt 5 -- we can't use Qt 6 because Ubuntu 22.04
    # doesn't have Qwt built for it yet.
    name: Build on Ubuntu 22.04
    runs-on: ubuntu-22.04
    steps:

    - uses: actions/checkout@v2

    - uses: actions/checkout@v2
      with:
        repository: happycube/ld-decode-testdata
        path: testdata

    - name: Install dependencies
      timeout-minutes: 10
      run: |
        sudo apt-get update
        # Based on: https://github.com/happycube/ld-decode/wiki/Installation
        # Added: cmake libqt5opengl5-dev libqt5svg5-dev
        sudo apt-get install -y --no-install-recommends git cmake make python3-distutils python3-numpy python3-scipy python3-matplotlib qtbase5-dev libqt5opengl5-dev libqt5svg5-dev libqwt-qt5-dev libfftw3-dev python3-numba libavformat-dev libavcodec-dev libavutil-dev ffmpeg

    - name: Set up build dir
      timeout-minutes: 1
      run: mkdir obj && ln -s ../testdata obj/testdata

    - name: Configure
      timeout-minutes: 5
      run: cd obj && cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo ..

    - name: Build
      timeout-minutes: 15
      run: make -C obj VERBOSE=1

    - name: Install
      timeout-minutes: 5
      run: make -C obj install DESTDIR=/tmp/staging && ls -lR /tmp/staging

    - name: Run tests
      timeout-minutes: 10
      run: cd obj && ctest --output-on-failure
